// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types.ts';

const SUPABASE_URL = "https://gzkrpbgyfiyvigjivexv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6a3JwYmd5Zml5dmlnaml2ZXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzE4OTcsImV4cCI6MjA2NzMwNzg5N30.e3fAjiTLhJOJh7mQ0nIWCLBVnwjFMm0RlWtxLc7ZtRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});